# Generated by Django 3.2.9 on 2021-12-17 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[['VESTIDO', 'Vestido'], ['CALÇA', 'Calça'], ['BLUSA', 'Blusa'], ['SHORT', 'Short']], max_length=50, verbose_name='Tipo')),
                ('tamanho', models.CharField(max_length=50, verbose_name='Tamanho')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Roupa',
                'verbose_name_plural': 'Roupas',
            },
        ),
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('restaurado', models.BooleanField(default=True, verbose_name='Restaurado')),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Costureira')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.roupa', verbose_name='Roupa')),
            ],
            options={
                'verbose_name': 'Reparo',
                'verbose_name_plural': 'Reparos',
            },
        ),
    ]
