# Generated by Django 3.2.9 on 2021-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparo',
            name='restaurado',
            field=models.BooleanField(default=False, verbose_name='Restaurado'),
        ),
    ]
