# Generated by Django 3.2.9 on 2021-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reparo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparo',
            name='data_entrega',
            field=models.DateField(null=True, verbose_name='Data de Entrega'),
        ),
    ]
