# Generated by Django 3.2.9 on 2021-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_reparo_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparo',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
    ]
