# Generated by Django 3.2.9 on 2021-12-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_reparo_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='imagem',
            field=models.ImageField(null=True, upload_to='roupas', verbose_name='Imagem'),
        ),
    ]
